kind: SecurityContextConstraints
apiVersion: v1
metadata:
  name: systemd-scc
allowPrivilegedContainer: true
defaultAddCapabilities: null
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
fsGroup:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny
users:
- system:serviceaccount:systemd:jenkins
groups:
